"""Compatibility re-export for runtime job sentinel strings."""

from __future__ import annotations

from common.runtime_job_status import (
    DAILY_RUN_STATUS_FAILED,
    DAILY_RUN_STATUS_SUCCESS,
    BURN_IN_STATUS_COMPLETE_SENTINEL,
    DAILY_BACKTEST_REFRESH_COMPLETE_SENTINEL,
    DAILY_CHALLENGER_SHADOW_EVAL_COMPLETE_SENTINEL,
    DAILY_PAPER_TRADING_COMPLETE_SENTINEL,
    DAILY_SNAPSHOT_COMPLETE_SENTINEL,
    WEEKLY_DB_BACKUP_COMPLETE_SENTINEL,
    WEEKLY_GOVERNANCE_W1_LEADERBOARD_COMPLETE_SENTINEL,
    WEEKLY_GOVERNANCE_W2_PROMOTION_REVIEW_COMPLETE_SENTINEL,
    WEEKLY_GOVERNANCE_W3_ALLOCATION_REVIEW_COMPLETE_SENTINEL,
    MONTHLY_GOVERNANCE_M1_RISK_REBASELINE_COMPLETE_SENTINEL,
    MONTHLY_GOVERNANCE_M2_PARAMETER_GOVERNANCE_COMPLETE_SENTINEL,
    MONTHLY_GOVERNANCE_M3_PERFORMANCE_AUDIT_COMPLETE_SENTINEL,
)

__all__ = [
    "DAILY_RUN_STATUS_FAILED",
    "DAILY_RUN_STATUS_SUCCESS",
    "BURN_IN_STATUS_COMPLETE_SENTINEL",
    "DAILY_BACKTEST_REFRESH_COMPLETE_SENTINEL",
    "DAILY_CHALLENGER_SHADOW_EVAL_COMPLETE_SENTINEL",
    "DAILY_PAPER_TRADING_COMPLETE_SENTINEL",
    "DAILY_SNAPSHOT_COMPLETE_SENTINEL",
    "WEEKLY_DB_BACKUP_COMPLETE_SENTINEL",
    "WEEKLY_GOVERNANCE_W1_LEADERBOARD_COMPLETE_SENTINEL",
    "WEEKLY_GOVERNANCE_W2_PROMOTION_REVIEW_COMPLETE_SENTINEL",
    "WEEKLY_GOVERNANCE_W3_ALLOCATION_REVIEW_COMPLETE_SENTINEL",
    "MONTHLY_GOVERNANCE_M1_RISK_REBASELINE_COMPLETE_SENTINEL",
    "MONTHLY_GOVERNANCE_M2_PARAMETER_GOVERNANCE_COMPLETE_SENTINEL",
    "MONTHLY_GOVERNANCE_M3_PERFORMANCE_AUDIT_COMPLETE_SENTINEL",
]
