"""Alembic environment for the trading database.

Connection-mode only: the migration runner (or a test helper) opens a
connection from the active ``DatabaseBackend`` and passes it through
``config.attributes["connection"]``. There is no URL/offline mode — database
path resolution stays owned by ``infrastructure.database.config``, and this
environment never resolves paths itself.
"""

from __future__ import annotations

from alembic import context


def _run_migrations() -> None:
    if context.is_offline_mode():
        raise RuntimeError(
            "Offline (--sql) mode is not supported; run migrations through infrastructure.database.migration_runner."
        )
    connection = context.config.attributes.get("connection")
    if connection is None:
        raise RuntimeError(
            "No connection supplied. Run migrations through "
            "infrastructure.database.migration_runner, which opens one from the "
            "active DatabaseBackend."
        )
    # No target_metadata: revisions are hand-authored, never autogenerated.
    # render_as_batch keeps future ALTERs on SQLite's copy-and-rebuild path.
    context.configure(connection=connection, target_metadata=None, render_as_batch=True)
    with context.begin_transaction():
        context.run_migrations()


_run_migrations()
